import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // src 폴더 기준으로 경로 추적(@ alias)
import getCurrentUser from './actions/getCurrentUser';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar currentUser={currentUser}/>
          {children}
      </body>
    </html>
  );
}
