version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    posrts:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/postgresql/data